#!/bin/bash


if [ -z "$1" ]; then
    echo "Error: No Bucket name provided."
    exit 1
fi

echo "First argument is: $1"

aws s3api delete-bucket --bucket "$1" --region eu-north-1

echo "Bucket $1 Deleted successfully."
